import gwagon from "../assets/gwagon.jpg"
import bmw from"../assets/bmw.jpg"
import mustang from"../assets/mustang.jpg"
import porche from "../assets/porche.jpg"
import subaru from "../assets/subaru.jpg"
import sedan from "../assets/sedan.jpg"
import vintage from "../assets/vintage.jpg"
import bluemustang from "../assets/bluemustang.jpg"
import audi from "../assets/audi.jpg"

export interface Car {
  id: number;
  name: string;
  description: string;
  image: string;
  rating: number;
  year: number;
  type: string;
  seats: number;
  luggage: number;
  doors: number;
  price: number;
  favorite: boolean;
}

export const carData: Car[] = [
  {
    id: 1,
    name: "Audi Q7",
    description: "Premium Plus",
    image: porche ,
    rating: 4.8,
    year: 2023,
    type: "SUV",
    seats: 7,
    luggage: 5,
    doors: 4,
    price: 250,
    favorite: false,
  },
  {
    id: 2,
    name: "Mercedes-Benz S-Class",
    description: "S 500 4MATIC",
    image: gwagon,
    rating: 4.6,
    year: 2023,
    type: "Sedan",
    seats: 5,
    luggage: 3,
    doors: 4,
    price: 400,
    favorite: false,
  },
  {
    id: 3,
    name: "Tesla Model 3",
    description: "Standard Range Plus",
    image: bmw ,
    rating: 4.9,
    year: 2023,
    type: "Sedan",
    seats: 5,
    luggage: 2,
    doors: 4,
    price: 199,
    favorite: false,
  },
  {
    id: 4,
    name: "BMW X5",
    description: "xDrive40i",
    image: mustang ,
    rating: 4.9,
    year: 2023,
    type: "SUV",
    seats: 5,
    luggage: 2,
    doors: 4,
    price: 220,
    favorite: false,
  },
  {
    id: 5,
    name: "Porsche Cayenne",
    description: "Turbo GT",
    image: porche,
    rating: 4.7,
    year: 2022,
    type: "SUV",
    seats: 4,
    luggage: 5,
    doors: 4,
    price: 380,
    favorite: false,
  },
  {
    id: 6,
    name: "Lamborghini Urus",
    description: "Urus",
    image: bmw,
    rating: 4.9,
    year: 2023,
    type: "SUV",
    seats: 5,
    luggage: 2,
    doors: 4,
    price: 999,
    favorite: false,
  },
  {
    id: 7,
    name: "Subaru Outback",
    description: "Touring XT",
    image: subaru,
    rating: 4.5,
    year: 2021,
    type: "Wagon",
    seats: 5,
    luggage: 4,
    doors: 4,
    price: 180,
    favorite: false,
  },
  {
    id: 8,
    name: "Vintage Classic",
    description: "Collector's Edition",
    image: vintage,
    rating: 4.2,
    year: 1972,
    type: "Coupe",
    seats: 2,
    luggage: 1,
    doors: 2,
    price: 320,
    favorite: false,
  },
  {
    id: 9,
    name: "Blue Mustang",
    description: "GT Premium",
    image: bluemustang,
    rating: 4.8,
    year: 2022,
    type: "Coupe",
    seats: 4,
    luggage: 2,
    doors: 2,
    price: 350,
    favorite: false,
  },
  {
    id: 10,
    name: "Audi A4",
    description: "Premium Sedan",
    image: audi,
    rating: 4.6,
    year: 2021,
    type: "Sedan",
    seats: 5,
    luggage: 3,
    doors: 4,
    price: 210,
    favorite: false,
  },
  {
    id: 11,
    name: "Volkswagen Passat",
    description: "Comfortline",
    image: sedan,
    rating: 4.4,
    year: 2020,
    type: "Sedan",
    seats: 5,
    luggage: 4,
    doors: 4,
    price: 170,
    favorite: false,
  },
  {
    id: 12,
    name: "Toyota Camry",
    description: "Hybrid XLE",
    image: sedan,
    rating: 4.7,
    year: 2022,
    type: "Sedan",
    seats: 5,
    luggage: 3,
    doors: 4,
    price: 230,
    favorite: false,
  },
  {
    id: 13,
    name: "Honda Accord",
    description: "Sport Special",
    image: sedan,
    rating: 4.8,
    year: 2023,
    type: "Sedan",
    seats: 5,
    luggage: 3,
    doors: 4,
    price: 240,
    favorite: false,
  },
  {
    id: 14,
    name: "Mazda CX-5",
    description: "Signature AWD",
    image: subaru,
    rating: 4.6,
    year: 2022,
    type: "SUV",
    seats: 5,
    luggage: 4,
    doors: 4,
    price: 200,
    favorite: false,
  },
  {
    id: 15,
    name: "Chevrolet Malibu",
    description: "LT Turbo",
    image: sedan,
    rating: 4.3,
    year: 2021,
    type: "Sedan",
    seats: 5,
    luggage: 3,
    doors: 4,
    price: 160,
    favorite: false,
  },
  {
    id: 16,
    name: "Ford Explorer",
    description: "Limited",
    image: gwagon,
    rating: 4.5,
    year: 2022,
    type: "SUV",
    seats: 7,
    luggage: 5,
    doors: 4,
    price: 270,
    favorite: false,
  },
  {
    id: 17,
    name: "Hyundai Sonata",
    description: "SEL Plus",
    image: sedan,
    rating: 4.4,
    year: 2021,
    type: "Sedan",
    seats: 5,
    luggage: 3,
    doors: 4,
    price: 175,
    favorite: false,
  },
  {
    id: 18,
    name: "Kia Sportage",
    description: "EX AWD",
    image: bmw,
    rating: 4.5,
    year: 2022,
    type: "SUV",
    seats: 5,
    luggage: 4,
    doors: 4,
    price: 210,
    favorite: false,
  },
  {
    id: 19,
    name: "Nissan Altima",
    description: "Platinum",
    image: sedan,
    rating: 4.3,
    year: 2021,
    type: "Sedan",
    seats: 5,
    luggage: 3,
    doors: 4,
    price: 165,
    favorite: false,
  },
  {
    id: 20,
    name: "Jeep Wrangler",
    description: "Rubicon",
    image: gwagon,
    rating: 4.7,
    year: 2023,
    type: "SUV",
    seats: 5,
    luggage: 2,
    doors: 4,
    price: 390,
    favorite: false,
  },
];
